# ============================================================================
#  demo2 - migration / model config (single source of truth)
#  ----------------------------------------------------------------------------
#  Moving to a new PC, changing ports, pointing at a different Ollama, or
#  swapping models? Edit ONLY this file.
#
#  Every scripts\*.ps1 dot-sources this on startup and applies the values.
#  After editing:
#    - just changing models / Ollama URL -> re-run .\scripts\start-booth.ps1
#    - changing port / profile           -> delete
#         ~/.openclaw-<profile>/openclaw.json, then re-run
#         bootstrap-profile.ps1 + install-plugins.ps1
#
#  NOTE: comments are ASCII-only on purpose. Windows PowerShell 5.1 mis-parses
#  UTF-8-without-BOM .ps1 files that contain non-ASCII (Chinese) bytes, which
#  silently breaks variable assignment. Keep this file ASCII.
#
#  Secrets are NOT here:
#    - Gateway token  -> .env.local (auto-generated by bootstrap, gitignored)
#    - WiFi / ESP32   -> arduino\esp32_sensor_node\secrets.h (gitignored)
# ============================================================================

# --- OpenClaw profile -------------------------------------------------------
# Isolation profile name -> maps to config dir ~/.openclaw-<profile>/.
# Renaming = a brand-new clean environment (must re-run bootstrap + install).
$DEMO2_PROFILE = "strixdemo2"

# --- Ports ------------------------------------------------------------------
$DEMO2_GATEWAY_PORT = 18790      # OpenClaw gateway (dashboard + all /api)
$DEMO2_HTTPS_PORT   = 18443      # HTTPS reverse proxy (phones via QR; localhost N/A)
$DEMO2_BRIDGE_PORT  = 8765       # Python mock bridge (only used in -Mock mode)

# --- Ollama / models --------------------------------------------------------
# Ollama HTTP API location. If Ollama runs on ANOTHER machine (e.g. the Strix
# Halo box while Surface is the frontend), set http://<that-ip>:11434
$DEMO2_OLLAMA_URL = "http://127.0.0.1:11434"

# Per-agent models. Before switching, `ollama pull <model>` on whichever
# machine runs Ollama. When the Strix Halo box arrives and you want gemma,
# this is the only place to change (judge can be a small text model; vision /
# vlm need a multimodal model):
$DEMO2_JUDGE_MODEL  = "qwen2:1.5b"      # anomaly -> one-line Chinese explanation
$DEMO2_VISION_MODEL = "qwen2.5vl:3b"    # auto-vision -> Chinese scene description
$DEMO2_VLM_MODEL    = "qwen2.5vl:3b"    # /vlm chat page -> multimodal conversation

# ----------------------------------------------------------------------------
# Derived values (do not edit) - used directly by scripts
# ----------------------------------------------------------------------------
$DEMO2_GATEWAY_URL = "http://127.0.0.1:$DEMO2_GATEWAY_PORT"
$DEMO2_PROFILE_DIR = Join-Path $env:USERPROFILE ".openclaw-$DEMO2_PROFILE"
